name: Merge swagger files into one single file

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./openapi-merge

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npx openapi-merge-cli
    - uses: actions/upload-artifact@v4
      name: Upload unified swagger file
      with:
        name: selling-partner-api-spec
        path: selling-partner-api.json
